// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace iCunOS.BillBoards {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("iCunOS.BillBoards.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WatchTheAd {
            get {
                return ResourceManager.GetString("WatchTheAd", resourceCulture);
            }
        }
        
        internal static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string MorePoints {
            get {
                return ResourceManager.GetString("MorePoints", resourceCulture);
            }
        }
        
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        internal static string ForMorePoints {
            get {
                return ResourceManager.GetString("ForMorePoints", resourceCulture);
            }
        }
        
        internal static string FbLogin {
            get {
                return ResourceManager.GetString("FbLogin", resourceCulture);
            }
        }
        
        internal static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        internal static string SayReject {
            get {
                return ResourceManager.GetString("SayReject", resourceCulture);
            }
        }
        
        internal static string BilboardPassDate {
            get {
                return ResourceManager.GetString("BilboardPassDate", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Advertisements {
            get {
                return ResourceManager.GetString("Advertisements", resourceCulture);
            }
        }
        
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        internal static string DontDownloadAd {
            get {
                return ResourceManager.GetString("DontDownloadAd", resourceCulture);
            }
        }
        
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        internal static string SkipMoreAd {
            get {
                return ResourceManager.GetString("SkipMoreAd", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string NotAccumulated {
            get {
                return ResourceManager.GetString("NotAccumulated", resourceCulture);
            }
        }
        
        internal static string AccumulatePoints {
            get {
                return ResourceManager.GetString("AccumulatePoints", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        internal static string StopJourney {
            get {
                return ResourceManager.GetString("StopJourney", resourceCulture);
            }
        }
        
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        internal static string DownloadAd {
            get {
                return ResourceManager.GetString("DownloadAd", resourceCulture);
            }
        }
        
        internal static string LoginInfo {
            get {
                return ResourceManager.GetString("LoginInfo", resourceCulture);
            }
        }
        
        internal static string CollectPoints {
            get {
                return ResourceManager.GetString("CollectPoints", resourceCulture);
            }
        }
        
        internal static string Auth {
            get {
                return ResourceManager.GetString("Auth", resourceCulture);
            }
        }
        
        internal static string RejectToWatchAd {
            get {
                return ResourceManager.GetString("RejectToWatchAd", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        internal static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string WeNeedAccessToYourEmailToConnectWithFB {
            get {
                return ResourceManager.GetString("WeNeedAccessToYourEmailToConnectWithFB", resourceCulture);
            }
        }
        
        internal static string NoInternetConnectionTryLater {
            get {
                return ResourceManager.GetString("NoInternetConnectionTryLater", resourceCulture);
            }
        }
        
        internal static string Abolish {
            get {
                return ResourceManager.GetString("Abolish", resourceCulture);
            }
        }
        
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        internal static string StartJourney {
            get {
                return ResourceManager.GetString("StartJourney", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string NotAccumulatedNotification {
            get {
                return ResourceManager.GetString("NotAccumulatedNotification", resourceCulture);
            }
        }
        
        internal static string ForSeeAd {
            get {
                return ResourceManager.GetString("ForSeeAd", resourceCulture);
            }
        }
        
        internal static string BilboardSeenTime {
            get {
                return ResourceManager.GetString("BilboardSeenTime", resourceCulture);
            }
        }
    }
}
