//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuni.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Kuni.Core.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string ProcessingRequest {
            get {
                return ResourceManager.GetString("ProcessingRequest", resourceCulture);
            }
        }
        
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        internal static string SubmittingOTP {
            get {
                return ResourceManager.GetString("SubmittingOTP", resourceCulture);
            }
        }
        
        internal static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        internal static string VerificationCodeIsNull {
            get {
                return ResourceManager.GetString("VerificationCodeIsNull", resourceCulture);
            }
        }
        
        internal static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string RemovePin {
            get {
                return ResourceManager.GetString("RemovePin", resourceCulture);
            }
        }
        
        internal static string RemovePinPageTitle {
            get {
                return ResourceManager.GetString("RemovePinPageTitle", resourceCulture);
            }
        }
        
        internal static string removed_pin_successfully {
            get {
                return ResourceManager.GetString("removed_pin_successfully", resourceCulture);
            }
        }
        
        internal static string incorrect_pin {
            get {
                return ResourceManager.GetString("incorrect_pin", resourceCulture);
            }
        }
        
        internal static string ChangePin {
            get {
                return ResourceManager.GetString("ChangePin", resourceCulture);
            }
        }
        
        internal static string ChangePinPageTitle {
            get {
                return ResourceManager.GetString("ChangePinPageTitle", resourceCulture);
            }
        }
        
        internal static string enter_new_pin {
            get {
                return ResourceManager.GetString("enter_new_pin", resourceCulture);
            }
        }
        
        internal static string repeat_new_pin {
            get {
                return ResourceManager.GetString("repeat_new_pin", resourceCulture);
            }
        }
        
        internal static string repeated_pin_incorrect {
            get {
                return ResourceManager.GetString("repeated_pin_incorrect", resourceCulture);
            }
        }
        
        internal static string pin_changed_successfully {
            get {
                return ResourceManager.GetString("pin_changed_successfully", resourceCulture);
            }
        }
        
        internal static string pin_set_successfully {
            get {
                return ResourceManager.GetString("pin_set_successfully", resourceCulture);
            }
        }
        
        internal static string set_pin {
            get {
                return ResourceManager.GetString("set_pin", resourceCulture);
            }
        }
        
        internal static string CorePasswordHint {
            get {
                return ResourceManager.GetString("CorePasswordHint", resourceCulture);
            }
        }
        
        internal static string ValidWithNoTransactions {
            get {
                return ResourceManager.GetString("ValidWithNoTransactions", resourceCulture);
            }
        }
    }
}
