// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Kunicardus.Touch {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Kunicardus.Touch.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EnterSMSCode {
            get {
                return ResourceManager.GetString("EnterSMSCode", resourceCulture);
            }
        }
        
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        internal static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        internal static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        internal static string Unimania {
            get {
                return ResourceManager.GetString("Unimania", resourceCulture);
            }
        }
        
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        internal static string SumTotal {
            get {
                return ResourceManager.GetString("SumTotal", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string ShareApp {
            get {
                return ResourceManager.GetString("ShareApp", resourceCulture);
            }
        }
        
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        internal static string Yeap {
            get {
                return ResourceManager.GetString("Yeap", resourceCulture);
            }
        }
        
        internal static string AroundMe {
            get {
                return ResourceManager.GetString("AroundMe", resourceCulture);
            }
        }
        
        internal static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string WithouPin {
            get {
                return ResourceManager.GetString("WithouPin", resourceCulture);
            }
        }
        
        internal static string SelectServiceCenter {
            get {
                return ResourceManager.GetString("SelectServiceCenter", resourceCulture);
            }
        }
        
        internal static string UWillGetSMSOnNumberBellow {
            get {
                return ResourceManager.GetString("UWillGetSMSOnNumberBellow", resourceCulture);
            }
        }
        
        internal static string set_pin {
            get {
                return ResourceManager.GetString("set_pin", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string ResendSMS {
            get {
                return ResourceManager.GetString("ResendSMS", resourceCulture);
            }
        }
        
        internal static string LastAdded {
            get {
                return ResourceManager.GetString("LastAdded", resourceCulture);
            }
        }
        
        internal static string Catalogue {
            get {
                return ResourceManager.GetString("Catalogue", resourceCulture);
            }
        }
        
        internal static string MobilePhoneNumber {
            get {
                return ResourceManager.GetString("MobilePhoneNumber", resourceCulture);
            }
        }
        
        internal static string SetPin {
            get {
                return ResourceManager.GetString("SetPin", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string ChangePin {
            get {
                return ResourceManager.GetString("ChangePin", resourceCulture);
            }
        }
        
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        internal static string GetPositive {
            get {
                return ResourceManager.GetString("GetPositive", resourceCulture);
            }
        }
        
        internal static string EnterLastTransactionDetails {
            get {
                return ResourceManager.GetString("EnterLastTransactionDetails", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string PriceRanges {
            get {
                return ResourceManager.GetString("PriceRanges", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        internal static string MyPage {
            get {
                return ResourceManager.GetString("MyPage", resourceCulture);
            }
        }
        
        internal static string UserNumberHint {
            get {
                return ResourceManager.GetString("UserNumberHint", resourceCulture);
            }
        }
        
        internal static string UHaveDiscounts {
            get {
                return ResourceManager.GetString("UHaveDiscounts", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string DoUHaveUnicard {
            get {
                return ResourceManager.GetString("DoUHaveUnicard", resourceCulture);
            }
        }
        
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        internal static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        internal static string Discounted {
            get {
                return ResourceManager.GetString("Discounted", resourceCulture);
            }
        }
        
        internal static string enter_pin {
            get {
                return ResourceManager.GetString("enter_pin", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        internal static string WeNeedAccessToYourEmailToConnectWithFB {
            get {
                return ResourceManager.GetString("WeNeedAccessToYourEmailToConnectWithFB", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        internal static string PersonalId {
            get {
                return ResourceManager.GetString("PersonalId", resourceCulture);
            }
        }
        
        internal static string SMSVerificationHint {
            get {
                return ResourceManager.GetString("SMSVerificationHint", resourceCulture);
            }
        }
        
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        internal static string EnterEmailAndPassword {
            get {
                return ResourceManager.GetString("EnterEmailAndPassword", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string RegisterPinCode {
            get {
                return ResourceManager.GetString("RegisterPinCode", resourceCulture);
            }
        }
        
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        internal static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        internal static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        internal static string MobilePhoneNumberDesc {
            get {
                return ResourceManager.GetString("MobilePhoneNumberDesc", resourceCulture);
            }
        }
        
        internal static string PhoneFormat {
            get {
                return ResourceManager.GetString("PhoneFormat", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string WhereToSpend {
            get {
                return ResourceManager.GetString("WhereToSpend", resourceCulture);
            }
        }
        
        internal static string Spent {
            get {
                return ResourceManager.GetString("Spent", resourceCulture);
            }
        }
        
        internal static string RemoveFilter {
            get {
                return ResourceManager.GetString("RemoveFilter", resourceCulture);
            }
        }
        
        internal static string EnterYourPersonalInformation {
            get {
                return ResourceManager.GetString("EnterYourPersonalInformation", resourceCulture);
            }
        }
        
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        internal static string ResponsiblePerson {
            get {
                return ResourceManager.GetString("ResponsiblePerson", resourceCulture);
            }
        }
        
        internal static string ObjectList {
            get {
                return ResourceManager.GetString("ObjectList", resourceCulture);
            }
        }
        
        internal static string ResponsiblePersonDesc {
            get {
                return ResourceManager.GetString("ResponsiblePersonDesc", resourceCulture);
            }
        }
        
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        internal static string RemovePin {
            get {
                return ResourceManager.GetString("RemovePin", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        internal static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        internal static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        internal static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        internal static string repeat_new_pin {
            get {
                return ResourceManager.GetString("repeat_new_pin", resourceCulture);
            }
        }
        
        internal static string enter_new_pin {
            get {
                return ResourceManager.GetString("enter_new_pin", resourceCulture);
            }
        }
        
        internal static string FacebookLogin {
            get {
                return ResourceManager.GetString("FacebookLogin", resourceCulture);
            }
        }
        
        internal static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        internal static string EnterInfomation {
            get {
                return ResourceManager.GetString("EnterInfomation", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string IncorrectPin {
            get {
                return ResourceManager.GetString("IncorrectPin", resourceCulture);
            }
        }
        
        internal static string DeliveryForm {
            get {
                return ResourceManager.GetString("DeliveryForm", resourceCulture);
            }
        }
        
        internal static string EnterUnicardNumber {
            get {
                return ResourceManager.GetString("EnterUnicardNumber", resourceCulture);
            }
        }
        
        internal static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
    }
}
